package com.example.filterapp

import jp.co.cyberagent.android.gpuimage.filter.*

object Constants {
//changing for git
    var imageFilters: ArrayList<ImageFilters> = ArrayList()



    fun getFiltersList(): ArrayList<ImageFilters>{
     //   imageFilters.add(ImageFilters("Spia",GPUImageSepiaToneFilter()))
        imageFilters.add(ImageFilters("Gray Scale",GPUImageGrayscaleFilter()))
     //   imageFilters.add(ImageFilters("Laplacian",GPUImageLaplacianFilter()))
        imageFilters.add(ImageFilters("Dilation",GPUImageDilationFilter()))
     //   imageFilters.add(ImageFilters("ZoomBlur", GPUImageZoomBlurFilter()))
        imageFilters.add(ImageFilters("Saturation", GPUImageSaturationFilter()))
        imageFilters.add(ImageFilters("Contrast", GPUImageContrastFilter()))
      //  imageFilters.add(ImageFilters("Brightness", GPUImageBrightnessFilter()))
      //  imageFilters.add(ImageFilters("Levels", GPUImageLevelsFilter()))
        imageFilters.add(ImageFilters("Exposure", GPUImageExposureFilter()))
      //  imageFilters.add(ImageFilters("RGB", GPUImageRGBFilter()))
        imageFilters.add(ImageFilters("RGB Dilation", GPUImageRGBDilationFilter()))
        imageFilters.add(ImageFilters("Hue", GPUImageHueFilter()))
        imageFilters.add(ImageFilters("White Balance", GPUImageWhiteBalanceFilter()))
        imageFilters.add(ImageFilters("Monochrome", GPUImageMonochromeFilter()))
        imageFilters.add(ImageFilters("False Color", GPUImageHueFilter()))
        imageFilters.add(ImageFilters("Sharpen", GPUImageSharpenFilter()))
     //   imageFilters.add(ImageFilters("Transform Operation", GPUImageTransformFilter()))
      //  imageFilters.add(ImageFilters("Gamma", GPUImageGammaFilter()))
        imageFilters.add(ImageFilters("Highlights ans Shadows", GPUImageHighlightShadowFilter()))
        imageFilters.add(ImageFilters("Haze", GPUImageHazeFilter()))
        imageFilters.add(ImageFilters("Color Inversion", GPUImageColorInvertFilter()))
        imageFilters.add(ImageFilters("Solarize", GPUImageSolarizeFilter()))
        imageFilters.add(ImageFilters("Vibrance", GPUImageVibranceFilter()))
        imageFilters.add(ImageFilters("Luminance", GPUImageLuminanceFilter()))
        imageFilters.add(ImageFilters("Luminance Threshold", GPUImageLuminanceThresholdFilter()))
     //   imageFilters.add(ImageFilters("Pixellate", GPUImagePixelationFilter()))
      //  imageFilters.add(ImageFilters("Halftone", GPUImageHalftoneFilter()))
       // imageFilters.add(ImageFilters("Crosshatch", GPUImageCrosshatchFilter()))
        imageFilters.add(ImageFilters("Sobel Edge Detection", GPUImageSobelEdgeDetectionFilter()))
        imageFilters.add(ImageFilters("Threshold Sobel Edge Detection", GPUImageSobelThresholdFilter()))
        imageFilters.add(ImageFilters("Sketch", GPUImageSketchFilter()))
        imageFilters.add(ImageFilters("Toon", GPUImageToonFilter()))
        imageFilters.add(ImageFilters("Smooth Toon Filter", GPUImageSmoothToonFilter()))
      //  imageFilters.add(ImageFilters("CGA ColorSpace", GPUImageCGAColorspaceFilter()))
      //  imageFilters.add(ImageFilters("Posterize", GPUImagePosterizeFilter()))
      //  imageFilters.add(ImageFilters("Convolution", GPUImage3x3ConvolutionFilter()))
        imageFilters.add(ImageFilters("Emboss", GPUImageEmbossFilter()))
        imageFilters.add(ImageFilters("Chroma Filter", GPUImageChromaKeyBlendFilter()))
        imageFilters.add(ImageFilters("Kuwaraha", GPUImageKuwaharaFilter()))
     //   imageFilters.add(ImageFilters("Vignette", GPUImageVignetteFilter()))
       // imageFilters.add(ImageFilters("Gaussian Blur", GPUImageGaussianBlurFilter()))
        //imageFilters.add(ImageFilters("Box Blur", GPUImageBoxBlurFilter()))
        //imageFilters.add(ImageFilters("Bilateral Blur", GPUImageBilateralBlurFilter()))
      //  imageFilters.add(ImageFilters("Swirl Distortion", GPUImageSwirlFilter()))
     //   imageFilters.add(ImageFilters("Sphere Refraction", GPUImageSphereRefractionFilter()))
      //  imageFilters.add(ImageFilters("Glass Sphere Refraction", GPUImageGlassSphereFilter()))
        imageFilters.add(ImageFilters("Dissolve Blend", GPUImageDissolveBlendFilter()))
        imageFilters.add(ImageFilters("Chroma Key Blend", GPUImageChromaKeyBlendFilter()))
      //  imageFilters.add(ImageFilters("Add Blend", GPUImageAddBlendFilter()))
      //  imageFilters.add(ImageFilters("Divide Blend", GPUImageDivideBlendFilter()))
      //  imageFilters.add(ImageFilters("Multiply Blend", GPUImageMultiplyBlendFilter()))
        imageFilters.add(ImageFilters("Overlay Blend", GPUImageOverlayBlendFilter()))
        imageFilters.add(ImageFilters("Lighten Blend", GPUImageLightenBlendFilter()))
      //  imageFilters.add(ImageFilters("Darken Blend", GPUImageDarkenBlendFilter()))
      //  imageFilters.add(ImageFilters("Color Burn Blend", GPUImageColorBurnBlendFilter()))
        imageFilters.add(ImageFilters("Color Dodge Blend", GPUImageColorDodgeBlendFilter()))
     //   imageFilters.add(ImageFilters("Linear Burn Blend", GPUImageLinearBurnBlendFilter()))
        imageFilters.add(ImageFilters("Screen Blend", GPUImageScreenBlendFilter()))
      //  imageFilters.add(ImageFilters("Difference Blend", GPUImageDifferenceBlendFilter()))
    //    imageFilters.add(ImageFilters("Subtract Blend", GPUImageSubtractBlendFilter()))
      //  imageFilters.add(ImageFilters("Exclusion Blend", GPUImageExclusionBlendFilter()))
     //   imageFilters.add(ImageFilters("HardLight Blend", GPUImageHardLightBlendFilter()))
        imageFilters.add(ImageFilters("SoftLight Blend", GPUImageSoftLightBlendFilter()))
        imageFilters.add(ImageFilters("Color Blend", GPUImageColorBlendFilter()))
        imageFilters.add(ImageFilters("Hue Blend", GPUImageHueBlendFilter()))
      //  imageFilters.add(ImageFilters("Saturation Blend", GPUImageSaturationBlendFilter()))
      //  imageFilters.add(ImageFilters("Luminosity Blend", GPUImageLuminosityBlendFilter()))
      //  imageFilters.add(ImageFilters("Normal Blend", GPUImageNormalBlendFilter()))
       // imageFilters.add(ImageFilters("Source Over Blend", GPUImageSourceOverBlendFilter()))
        imageFilters.add(ImageFilters("Alpha Blend", GPUImageAlphaBlendFilter()))
     //   imageFilters.add(ImageFilters("Non Maximum Suppression", GPUImageNonMaximumSuppressionFilter()))
        imageFilters.add(ImageFilters("Opacity", GPUImageOpacityFilter()))
      //  imageFilters.add(ImageFilters("Weak Pixel Inclusion Filter", GPUImageWeakPixelInclusionFilter()))
        imageFilters.add(ImageFilters("Color Matrix", GPUImageColorMatrixFilter()))
      //  imageFilters.add(ImageFilters("Directional Sobel Edge Detection", GPUImageDirectionalSobelEdgeDetectionFilter()))
      //  imageFilters.add(ImageFilters("Lookup", GPUImageLookupFilter()))
        imageFilters.add(ImageFilters("Tone Curve", GPUImageToneCurveFilter()))
   
        return imageFilters
    }
}